environment:
  ANDROID_HOME: "C:\\android"
  nodejs_version: "4"

image:
- Previous Visual Studio 2015
- Visual Studio 2015


#image: Previous Visual Studio 2015

init:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
  #- wusa /uninstall /quiet /norestart /kb:4033428
  #- wusa /uninstall /quiet /forcerestart /kb:4025336
  #- ps: restart-computer -f
  
  - mkdir "%ANDROID_HOME%
  - cd "%ANDROID_HOME%"
  - appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip"
  - 7z x "tools_r25.2.3-windows.zip" > nul
  - cd "C:\projects\cordova-android"  

install:
  #- choco install gradle -version 3.4.1
  - choco install gradle
  - gradle -version
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-26.0.0,android-26,android-25,extra-google-m2repository,extra-android-m2repository
  # on windows we need to accept sublicenses for the new tooling, wee. 30 is an arbitrary number,
  # but should be the maximum number of licenses we explicitly need to type "Y ENTER" for.
  # also, the sdkmanager in all its glory leaks a bit of output to stderr, and powershell
  # and appveyor interpret that as errors, and blows up. so, when piping in our "Y ENTER"
  # responses, we invoke cmd so we can redirect stderr to stdout, and tell it to --update itself.
  - ps: for($i=0;$i -lt 30;$i++) { $response += "y`n"}; $response | cmd /c 'C:\android\tools\bin\sdkmanager.bat 2>&1' --update
  - cd test
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- NetSh Advfirewall set allprofiles state off
  - ps: Get-WmiObject Win32_Process -Filter "name = 'adb.exe'"
  - ps: gradle :wrapper -b build.gradl
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cd ..
  - ps: Install-Product node $env:nodejs_version
  - npm install
  

build: off

test_script:
  - node --version
  - npm --version
  - npm test

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
